name: whisper_flutter
description: A flutter library for offline speech-to-text conversion which use whisper.cpp models implementation for Android.
version: 0.0.1
homepage: https://github.com/CodeSagePath/whisper_flutter
repository: https://github.com/CodeSagePath/whisper_flutter
issue_tracker: https://github.com/CodeSagePath/whisper_flutter/issues
topics:
  - audio
  - speech
  - transcription
  - ai-tools

platforms:
  android:
  ios:
  macos:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  plugin_platform_interface: ^2.1.8


dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  ffigen: ^14.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true